// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.4
// source: proto/admin.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AdminInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           int64                  `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	ExtraInfo     map[string]string      `protobuf:"bytes,4,rep,name=extra_info,json=extraInfo,proto3" json:"extra_info,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminInfo) Reset() {
	*x = AdminInfo{}
	mi := &file_proto_admin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminInfo) ProtoMessage() {}

func (x *AdminInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminInfo.ProtoReflect.Descriptor instead.
func (*AdminInfo) Descriptor() ([]byte, []int) {
	return file_proto_admin_proto_rawDescGZIP(), []int{0}
}

func (x *AdminInfo) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *AdminInfo) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *AdminInfo) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *AdminInfo) GetExtraInfo() map[string]string {
	if x != nil {
		return x.ExtraInfo
	}
	return nil
}

type UserInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           int64                  `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Score         uint32                 `protobuf:"varint,2,opt,name=score,proto3" json:"score,omitempty"`
	Username      string                 `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	Email         string                 `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	Status        uint64                 `protobuf:"varint,5,opt,name=status,proto3" json:"status,omitempty"`
	ExtraInfo     map[string]string      `protobuf:"bytes,6,rep,name=extra_info,json=extraInfo,proto3" json:"extra_info,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserInfo) Reset() {
	*x = UserInfo{}
	mi := &file_proto_admin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfo) ProtoMessage() {}

func (x *UserInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfo.ProtoReflect.Descriptor instead.
func (*UserInfo) Descriptor() ([]byte, []int) {
	return file_proto_admin_proto_rawDescGZIP(), []int{1}
}

func (x *UserInfo) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *UserInfo) GetScore() uint32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *UserInfo) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UserInfo) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserInfo) GetStatus() uint64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *UserInfo) GetExtraInfo() map[string]string {
	if x != nil {
		return x.ExtraInfo
	}
	return nil
}

type GetUserReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           int64                  `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserReq) Reset() {
	*x = GetUserReq{}
	mi := &file_proto_admin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserReq) ProtoMessage() {}

func (x *GetUserReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserReq.ProtoReflect.Descriptor instead.
func (*GetUserReq) Descriptor() ([]byte, []int) {
	return file_proto_admin_proto_rawDescGZIP(), []int{2}
}

func (x *GetUserReq) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

type GetUserResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *UserInfo              `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Found         bool                   `protobuf:"varint,2,opt,name=found,proto3" json:"found,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserResp) Reset() {
	*x = GetUserResp{}
	mi := &file_proto_admin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserResp) ProtoMessage() {}

func (x *GetUserResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserResp.ProtoReflect.Descriptor instead.
func (*GetUserResp) Descriptor() ([]byte, []int) {
	return file_proto_admin_proto_rawDescGZIP(), []int{3}
}

func (x *GetUserResp) GetUser() *UserInfo {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *GetUserResp) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

type GetSelfReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           int64                  `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSelfReq) Reset() {
	*x = GetSelfReq{}
	mi := &file_proto_admin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSelfReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSelfReq) ProtoMessage() {}

func (x *GetSelfReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSelfReq.ProtoReflect.Descriptor instead.
func (*GetSelfReq) Descriptor() ([]byte, []int) {
	return file_proto_admin_proto_rawDescGZIP(), []int{4}
}

func (x *GetSelfReq) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

type GetSelfResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Admin         *AdminInfo             `protobuf:"bytes,1,opt,name=admin,proto3" json:"admin,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSelfResp) Reset() {
	*x = GetSelfResp{}
	mi := &file_proto_admin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSelfResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSelfResp) ProtoMessage() {}

func (x *GetSelfResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSelfResp.ProtoReflect.Descriptor instead.
func (*GetSelfResp) Descriptor() ([]byte, []int) {
	return file_proto_admin_proto_rawDescGZIP(), []int{5}
}

func (x *GetSelfResp) GetAdmin() *AdminInfo {
	if x != nil {
		return x.Admin
	}
	return nil
}

type CreateAdminReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	ExtraInfo     map[string]string      `protobuf:"bytes,4,rep,name=extra_info,json=extraInfo,proto3" json:"extra_info,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAdminReq) Reset() {
	*x = CreateAdminReq{}
	mi := &file_proto_admin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAdminReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAdminReq) ProtoMessage() {}

func (x *CreateAdminReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAdminReq.ProtoReflect.Descriptor instead.
func (*CreateAdminReq) Descriptor() ([]byte, []int) {
	return file_proto_admin_proto_rawDescGZIP(), []int{6}
}

func (x *CreateAdminReq) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *CreateAdminReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *CreateAdminReq) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CreateAdminReq) GetExtraInfo() map[string]string {
	if x != nil {
		return x.ExtraInfo
	}
	return nil
}

type CreateAdminResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           int64                  `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAdminResp) Reset() {
	*x = CreateAdminResp{}
	mi := &file_proto_admin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAdminResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAdminResp) ProtoMessage() {}

func (x *CreateAdminResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAdminResp.ProtoReflect.Descriptor instead.
func (*CreateAdminResp) Descriptor() ([]byte, []int) {
	return file_proto_admin_proto_rawDescGZIP(), []int{7}
}

func (x *CreateAdminResp) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

type LoginReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginReq) Reset() {
	*x = LoginReq{}
	mi := &file_proto_admin_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginReq) ProtoMessage() {}

func (x *LoginReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginReq.ProtoReflect.Descriptor instead.
func (*LoginReq) Descriptor() ([]byte, []int) {
	return file_proto_admin_proto_rawDescGZIP(), []int{8}
}

func (x *LoginReq) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *LoginReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           int64                  `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResp) Reset() {
	*x = LoginResp{}
	mi := &file_proto_admin_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResp) ProtoMessage() {}

func (x *LoginResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResp.ProtoReflect.Descriptor instead.
func (*LoginResp) Descriptor() ([]byte, []int) {
	return file_proto_admin_proto_rawDescGZIP(), []int{9}
}

func (x *LoginResp) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

type DeleteUserReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           int64                  `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserReq) Reset() {
	*x = DeleteUserReq{}
	mi := &file_proto_admin_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserReq) ProtoMessage() {}

func (x *DeleteUserReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserReq.ProtoReflect.Descriptor instead.
func (*DeleteUserReq) Descriptor() ([]byte, []int) {
	return file_proto_admin_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteUserReq) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

type DeleteUserResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserResp) Reset() {
	*x = DeleteUserResp{}
	mi := &file_proto_admin_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserResp) ProtoMessage() {}

func (x *DeleteUserResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserResp.ProtoReflect.Descriptor instead.
func (*DeleteUserResp) Descriptor() ([]byte, []int) {
	return file_proto_admin_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteUserResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type ResetUserPasswordReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           int64                  `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetUserPasswordReq) Reset() {
	*x = ResetUserPasswordReq{}
	mi := &file_proto_admin_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetUserPasswordReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetUserPasswordReq) ProtoMessage() {}

func (x *ResetUserPasswordReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetUserPasswordReq.ProtoReflect.Descriptor instead.
func (*ResetUserPasswordReq) Descriptor() ([]byte, []int) {
	return file_proto_admin_proto_rawDescGZIP(), []int{12}
}

func (x *ResetUserPasswordReq) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

type ResetUserPasswordResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetUserPasswordResp) Reset() {
	*x = ResetUserPasswordResp{}
	mi := &file_proto_admin_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetUserPasswordResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetUserPasswordResp) ProtoMessage() {}

func (x *ResetUserPasswordResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetUserPasswordResp.ProtoReflect.Descriptor instead.
func (*ResetUserPasswordResp) Descriptor() ([]byte, []int) {
	return file_proto_admin_proto_rawDescGZIP(), []int{13}
}

func (x *ResetUserPasswordResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type UpdateSelfReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           int64                  `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	Email         string                 `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	ExtraInfo     map[string]string      `protobuf:"bytes,5,rep,name=extra_info,json=extraInfo,proto3" json:"extra_info,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSelfReq) Reset() {
	*x = UpdateSelfReq{}
	mi := &file_proto_admin_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSelfReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSelfReq) ProtoMessage() {}

func (x *UpdateSelfReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSelfReq.ProtoReflect.Descriptor instead.
func (*UpdateSelfReq) Descriptor() ([]byte, []int) {
	return file_proto_admin_proto_rawDescGZIP(), []int{14}
}

func (x *UpdateSelfReq) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *UpdateSelfReq) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UpdateSelfReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *UpdateSelfReq) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UpdateSelfReq) GetExtraInfo() map[string]string {
	if x != nil {
		return x.ExtraInfo
	}
	return nil
}

type UpdateSelfResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Admin         *AdminInfo             `protobuf:"bytes,2,opt,name=admin,proto3" json:"admin,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSelfResp) Reset() {
	*x = UpdateSelfResp{}
	mi := &file_proto_admin_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSelfResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSelfResp) ProtoMessage() {}

func (x *UpdateSelfResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSelfResp.ProtoReflect.Descriptor instead.
func (*UpdateSelfResp) Descriptor() ([]byte, []int) {
	return file_proto_admin_proto_rawDescGZIP(), []int{15}
}

func (x *UpdateSelfResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpdateSelfResp) GetAdmin() *AdminInfo {
	if x != nil {
		return x.Admin
	}
	return nil
}

type UpdateUserReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           int64                  `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	Email         string                 `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	ExtraInfo     map[string]string      `protobuf:"bytes,5,rep,name=extra_info,json=extraInfo,proto3" json:"extra_info,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserReq) Reset() {
	*x = UpdateUserReq{}
	mi := &file_proto_admin_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserReq) ProtoMessage() {}

func (x *UpdateUserReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserReq.ProtoReflect.Descriptor instead.
func (*UpdateUserReq) Descriptor() ([]byte, []int) {
	return file_proto_admin_proto_rawDescGZIP(), []int{16}
}

func (x *UpdateUserReq) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *UpdateUserReq) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UpdateUserReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *UpdateUserReq) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UpdateUserReq) GetExtraInfo() map[string]string {
	if x != nil {
		return x.ExtraInfo
	}
	return nil
}

type UpdateUserResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	User          *UserInfo              `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserResp) Reset() {
	*x = UpdateUserResp{}
	mi := &file_proto_admin_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserResp) ProtoMessage() {}

func (x *UpdateUserResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserResp.ProtoReflect.Descriptor instead.
func (*UpdateUserResp) Descriptor() ([]byte, []int) {
	return file_proto_admin_proto_rawDescGZIP(), []int{17}
}

func (x *UpdateUserResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpdateUserResp) GetUser() *UserInfo {
	if x != nil {
		return x.User
	}
	return nil
}

type GetUserListReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int64                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int64                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Keyword       string                 `protobuf:"bytes,3,opt,name=keyword,proto3" json:"keyword,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserListReq) Reset() {
	*x = GetUserListReq{}
	mi := &file_proto_admin_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserListReq) ProtoMessage() {}

func (x *GetUserListReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserListReq.ProtoReflect.Descriptor instead.
func (*GetUserListReq) Descriptor() ([]byte, []int) {
	return file_proto_admin_proto_rawDescGZIP(), []int{18}
}

func (x *GetUserListReq) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetUserListReq) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *GetUserListReq) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

type GetUserListResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*UserInfo            `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserListResp) Reset() {
	*x = GetUserListResp{}
	mi := &file_proto_admin_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserListResp) ProtoMessage() {}

func (x *GetUserListResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserListResp.ProtoReflect.Descriptor instead.
func (*GetUserListResp) Descriptor() ([]byte, []int) {
	return file_proto_admin_proto_rawDescGZIP(), []int{19}
}

func (x *GetUserListResp) GetList() []*UserInfo {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *GetUserListResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type BanUserReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           int64                  `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BanUserReq) Reset() {
	*x = BanUserReq{}
	mi := &file_proto_admin_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BanUserReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BanUserReq) ProtoMessage() {}

func (x *BanUserReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BanUserReq.ProtoReflect.Descriptor instead.
func (*BanUserReq) Descriptor() ([]byte, []int) {
	return file_proto_admin_proto_rawDescGZIP(), []int{20}
}

func (x *BanUserReq) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

type BanUserResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BanUserResp) Reset() {
	*x = BanUserResp{}
	mi := &file_proto_admin_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BanUserResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BanUserResp) ProtoMessage() {}

func (x *BanUserResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BanUserResp.ProtoReflect.Descriptor instead.
func (*BanUserResp) Descriptor() ([]byte, []int) {
	return file_proto_admin_proto_rawDescGZIP(), []int{21}
}

func (x *BanUserResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type UnBanUserReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           int64                  `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnBanUserReq) Reset() {
	*x = UnBanUserReq{}
	mi := &file_proto_admin_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnBanUserReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnBanUserReq) ProtoMessage() {}

func (x *UnBanUserReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnBanUserReq.ProtoReflect.Descriptor instead.
func (*UnBanUserReq) Descriptor() ([]byte, []int) {
	return file_proto_admin_proto_rawDescGZIP(), []int{22}
}

func (x *UnBanUserReq) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

type UnBanUserResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnBanUserResp) Reset() {
	*x = UnBanUserResp{}
	mi := &file_proto_admin_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnBanUserResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnBanUserResp) ProtoMessage() {}

func (x *UnBanUserResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnBanUserResp.ProtoReflect.Descriptor instead.
func (*UnBanUserResp) Descriptor() ([]byte, []int) {
	return file_proto_admin_proto_rawDescGZIP(), []int{23}
}

func (x *UnBanUserResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_proto_admin_proto protoreflect.FileDescriptor

const file_proto_admin_proto_rawDesc = "" +
	"\n" +
	"\x11proto/admin.proto\x12\x05admin\"\xcd\x01\n" +
	"\tAdminInfo\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\x03R\x03uid\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12>\n" +
	"\n" +
	"extra_info\x18\x04 \x03(\v2\x1f.admin.AdminInfo.ExtraInfoEntryR\textraInfo\x1a<\n" +
	"\x0eExtraInfoEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xf9\x01\n" +
	"\bUserInfo\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\x03R\x03uid\x12\x14\n" +
	"\x05score\x18\x02 \x01(\rR\x05score\x12\x1a\n" +
	"\busername\x18\x03 \x01(\tR\busername\x12\x14\n" +
	"\x05email\x18\x04 \x01(\tR\x05email\x12\x16\n" +
	"\x06status\x18\x05 \x01(\x04R\x06status\x12=\n" +
	"\n" +
	"extra_info\x18\x06 \x03(\v2\x1e.admin.UserInfo.ExtraInfoEntryR\textraInfo\x1a<\n" +
	"\x0eExtraInfoEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x1e\n" +
	"\n" +
	"GetUserReq\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\x03R\x03uid\"H\n" +
	"\vGetUserResp\x12#\n" +
	"\x04user\x18\x01 \x01(\v2\x0f.admin.UserInfoR\x04user\x12\x14\n" +
	"\x05found\x18\x02 \x01(\bR\x05found\"\x1e\n" +
	"\n" +
	"GetSelfReq\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\x03R\x03uid\"5\n" +
	"\vGetSelfResp\x12&\n" +
	"\x05admin\x18\x01 \x01(\v2\x10.admin.AdminInfoR\x05admin\"\xe1\x01\n" +
	"\x0eCreateAdminReq\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12C\n" +
	"\n" +
	"extra_info\x18\x04 \x03(\v2$.admin.CreateAdminReq.ExtraInfoEntryR\textraInfo\x1a<\n" +
	"\x0eExtraInfoEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"#\n" +
	"\x0fCreateAdminResp\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\x03R\x03uid\"B\n" +
	"\bLoginReq\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"\x1d\n" +
	"\tLoginResp\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\x03R\x03uid\"!\n" +
	"\rDeleteUserReq\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\x03R\x03uid\"*\n" +
	"\x0eDeleteUserResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"(\n" +
	"\x14ResetUserPasswordReq\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\x03R\x03uid\"1\n" +
	"\x15ResetUserPasswordResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\xf1\x01\n" +
	"\rUpdateSelfReq\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\x03R\x03uid\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\x12\x14\n" +
	"\x05email\x18\x04 \x01(\tR\x05email\x12B\n" +
	"\n" +
	"extra_info\x18\x05 \x03(\v2#.admin.UpdateSelfReq.ExtraInfoEntryR\textraInfo\x1a<\n" +
	"\x0eExtraInfoEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"R\n" +
	"\x0eUpdateSelfResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12&\n" +
	"\x05admin\x18\x02 \x01(\v2\x10.admin.AdminInfoR\x05admin\"\xf1\x01\n" +
	"\rUpdateUserReq\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\x03R\x03uid\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\x12\x14\n" +
	"\x05email\x18\x04 \x01(\tR\x05email\x12B\n" +
	"\n" +
	"extra_info\x18\x05 \x03(\v2#.admin.UpdateUserReq.ExtraInfoEntryR\textraInfo\x1a<\n" +
	"\x0eExtraInfoEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"O\n" +
	"\x0eUpdateUserResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\x04user\x18\x02 \x01(\v2\x0f.admin.UserInfoR\x04user\"[\n" +
	"\x0eGetUserListReq\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x03R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x03R\bpageSize\x12\x18\n" +
	"\akeyword\x18\x03 \x01(\tR\akeyword\"L\n" +
	"\x0fGetUserListResp\x12#\n" +
	"\x04list\x18\x01 \x03(\v2\x0f.admin.UserInfoR\x04list\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"\x1e\n" +
	"\n" +
	"BanUserReq\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\x03R\x03uid\"'\n" +
	"\vBanUserResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\" \n" +
	"\fUnBanUserReq\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\x03R\x03uid\")\n" +
	"\rUnBanUserResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\x85\x05\n" +
	"\fAdminService\x120\n" +
	"\aGetUser\x12\x11.admin.GetUserReq\x1a\x12.admin.GetUserResp\x12<\n" +
	"\vGetUserList\x12\x15.admin.GetUserListReq\x1a\x16.admin.GetUserListResp\x120\n" +
	"\aGetSelf\x12\x11.admin.GetSelfReq\x1a\x12.admin.GetSelfResp\x12<\n" +
	"\vCreateAdmin\x12\x15.admin.CreateAdminReq\x1a\x16.admin.CreateAdminResp\x12*\n" +
	"\x05Login\x12\x0f.admin.LoginReq\x1a\x10.admin.LoginResp\x129\n" +
	"\n" +
	"DeleteUser\x12\x14.admin.DeleteUserReq\x1a\x15.admin.DeleteUserResp\x12N\n" +
	"\x11ResetUserPassword\x12\x1b.admin.ResetUserPasswordReq\x1a\x1c.admin.ResetUserPasswordResp\x129\n" +
	"\n" +
	"UpdateSelf\x12\x14.admin.UpdateSelfReq\x1a\x15.admin.UpdateSelfResp\x129\n" +
	"\n" +
	"UpdateUser\x12\x14.admin.UpdateUserReq\x1a\x15.admin.UpdateUserResp\x120\n" +
	"\aBanUser\x12\x11.admin.BanUserReq\x1a\x12.admin.BanUserResp\x126\n" +
	"\tUnBanUser\x12\x13.admin.UnBanUserReq\x1a\x14.admin.UnBanUserRespB\x06Z\x04./pbb\x06proto3"

var (
	file_proto_admin_proto_rawDescOnce sync.Once
	file_proto_admin_proto_rawDescData []byte
)

func file_proto_admin_proto_rawDescGZIP() []byte {
	file_proto_admin_proto_rawDescOnce.Do(func() {
		file_proto_admin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_admin_proto_rawDesc), len(file_proto_admin_proto_rawDesc)))
	})
	return file_proto_admin_proto_rawDescData
}

var file_proto_admin_proto_msgTypes = make([]protoimpl.MessageInfo, 29)
var file_proto_admin_proto_goTypes = []any{
	(*AdminInfo)(nil),             // 0: admin.AdminInfo
	(*UserInfo)(nil),              // 1: admin.UserInfo
	(*GetUserReq)(nil),            // 2: admin.GetUserReq
	(*GetUserResp)(nil),           // 3: admin.GetUserResp
	(*GetSelfReq)(nil),            // 4: admin.GetSelfReq
	(*GetSelfResp)(nil),           // 5: admin.GetSelfResp
	(*CreateAdminReq)(nil),        // 6: admin.CreateAdminReq
	(*CreateAdminResp)(nil),       // 7: admin.CreateAdminResp
	(*LoginReq)(nil),              // 8: admin.LoginReq
	(*LoginResp)(nil),             // 9: admin.LoginResp
	(*DeleteUserReq)(nil),         // 10: admin.DeleteUserReq
	(*DeleteUserResp)(nil),        // 11: admin.DeleteUserResp
	(*ResetUserPasswordReq)(nil),  // 12: admin.ResetUserPasswordReq
	(*ResetUserPasswordResp)(nil), // 13: admin.ResetUserPasswordResp
	(*UpdateSelfReq)(nil),         // 14: admin.UpdateSelfReq
	(*UpdateSelfResp)(nil),        // 15: admin.UpdateSelfResp
	(*UpdateUserReq)(nil),         // 16: admin.UpdateUserReq
	(*UpdateUserResp)(nil),        // 17: admin.UpdateUserResp
	(*GetUserListReq)(nil),        // 18: admin.GetUserListReq
	(*GetUserListResp)(nil),       // 19: admin.GetUserListResp
	(*BanUserReq)(nil),            // 20: admin.BanUserReq
	(*BanUserResp)(nil),           // 21: admin.BanUserResp
	(*UnBanUserReq)(nil),          // 22: admin.UnBanUserReq
	(*UnBanUserResp)(nil),         // 23: admin.UnBanUserResp
	nil,                           // 24: admin.AdminInfo.ExtraInfoEntry
	nil,                           // 25: admin.UserInfo.ExtraInfoEntry
	nil,                           // 26: admin.CreateAdminReq.ExtraInfoEntry
	nil,                           // 27: admin.UpdateSelfReq.ExtraInfoEntry
	nil,                           // 28: admin.UpdateUserReq.ExtraInfoEntry
}
var file_proto_admin_proto_depIdxs = []int32{
	24, // 0: admin.AdminInfo.extra_info:type_name -> admin.AdminInfo.ExtraInfoEntry
	25, // 1: admin.UserInfo.extra_info:type_name -> admin.UserInfo.ExtraInfoEntry
	1,  // 2: admin.GetUserResp.user:type_name -> admin.UserInfo
	0,  // 3: admin.GetSelfResp.admin:type_name -> admin.AdminInfo
	26, // 4: admin.CreateAdminReq.extra_info:type_name -> admin.CreateAdminReq.ExtraInfoEntry
	27, // 5: admin.UpdateSelfReq.extra_info:type_name -> admin.UpdateSelfReq.ExtraInfoEntry
	0,  // 6: admin.UpdateSelfResp.admin:type_name -> admin.AdminInfo
	28, // 7: admin.UpdateUserReq.extra_info:type_name -> admin.UpdateUserReq.ExtraInfoEntry
	1,  // 8: admin.UpdateUserResp.user:type_name -> admin.UserInfo
	1,  // 9: admin.GetUserListResp.list:type_name -> admin.UserInfo
	2,  // 10: admin.AdminService.GetUser:input_type -> admin.GetUserReq
	18, // 11: admin.AdminService.GetUserList:input_type -> admin.GetUserListReq
	4,  // 12: admin.AdminService.GetSelf:input_type -> admin.GetSelfReq
	6,  // 13: admin.AdminService.CreateAdmin:input_type -> admin.CreateAdminReq
	8,  // 14: admin.AdminService.Login:input_type -> admin.LoginReq
	10, // 15: admin.AdminService.DeleteUser:input_type -> admin.DeleteUserReq
	12, // 16: admin.AdminService.ResetUserPassword:input_type -> admin.ResetUserPasswordReq
	14, // 17: admin.AdminService.UpdateSelf:input_type -> admin.UpdateSelfReq
	16, // 18: admin.AdminService.UpdateUser:input_type -> admin.UpdateUserReq
	20, // 19: admin.AdminService.BanUser:input_type -> admin.BanUserReq
	22, // 20: admin.AdminService.UnBanUser:input_type -> admin.UnBanUserReq
	3,  // 21: admin.AdminService.GetUser:output_type -> admin.GetUserResp
	19, // 22: admin.AdminService.GetUserList:output_type -> admin.GetUserListResp
	5,  // 23: admin.AdminService.GetSelf:output_type -> admin.GetSelfResp
	7,  // 24: admin.AdminService.CreateAdmin:output_type -> admin.CreateAdminResp
	9,  // 25: admin.AdminService.Login:output_type -> admin.LoginResp
	11, // 26: admin.AdminService.DeleteUser:output_type -> admin.DeleteUserResp
	13, // 27: admin.AdminService.ResetUserPassword:output_type -> admin.ResetUserPasswordResp
	15, // 28: admin.AdminService.UpdateSelf:output_type -> admin.UpdateSelfResp
	17, // 29: admin.AdminService.UpdateUser:output_type -> admin.UpdateUserResp
	21, // 30: admin.AdminService.BanUser:output_type -> admin.BanUserResp
	23, // 31: admin.AdminService.UnBanUser:output_type -> admin.UnBanUserResp
	21, // [21:32] is the sub-list for method output_type
	10, // [10:21] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_proto_admin_proto_init() }
func file_proto_admin_proto_init() {
	if File_proto_admin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_admin_proto_rawDesc), len(file_proto_admin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   29,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_admin_proto_goTypes,
		DependencyIndexes: file_proto_admin_proto_depIdxs,
		MessageInfos:      file_proto_admin_proto_msgTypes,
	}.Build()
	File_proto_admin_proto = out.File
	file_proto_admin_proto_goTypes = nil
	file_proto_admin_proto_depIdxs = nil
}
