// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: admin.proto

package adminservice

import (
	"context"
	"sea-try-go/service/user/admin/rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AdminInfo             = pb.AdminInfo
	BanUserReq            = pb.BanUserReq
	BanUserResp           = pb.BanUserResp
	CreateAdminReq        = pb.CreateAdminReq
	CreateAdminResp       = pb.CreateAdminResp
	DeleteUserReq         = pb.DeleteUserReq
	DeleteUserResp        = pb.DeleteUserResp
	GetSelfReq            = pb.GetSelfReq
	GetSelfResp           = pb.GetSelfResp
	GetUserListReq        = pb.GetUserListReq
	GetUserListResp       = pb.GetUserListResp
	GetUserReq            = pb.GetUserReq
	GetUserResp           = pb.GetUserResp
	LoginReq              = pb.LoginReq
	LoginResp             = pb.LoginResp
	ResetUserPasswordReq  = pb.ResetUserPasswordReq
	ResetUserPasswordResp = pb.ResetUserPasswordResp
	UnBanUserReq          = pb.UnBanUserReq
	UnBanUserResp         = pb.UnBanUserResp
	UpdateSelfReq         = pb.UpdateSelfReq
	UpdateSelfResp        = pb.UpdateSelfResp
	UpdateUserReq         = pb.UpdateUserReq
	UpdateUserResp        = pb.UpdateUserResp
	UserInfo              = pb.UserInfo

	AdminService interface {
		GetUser(ctx context.Context, in *GetUserReq, opts ...grpc.CallOption) (*GetUserResp, error)
		GetUserList(ctx context.Context, in *GetUserListReq, opts ...grpc.CallOption) (*GetUserListResp, error)
		GetSelf(ctx context.Context, in *GetSelfReq, opts ...grpc.CallOption) (*GetSelfResp, error)
		CreateAdmin(ctx context.Context, in *CreateAdminReq, opts ...grpc.CallOption) (*CreateAdminResp, error)
		Login(ctx context.Context, in *LoginReq, opts ...grpc.CallOption) (*LoginResp, error)
		DeleteUser(ctx context.Context, in *DeleteUserReq, opts ...grpc.CallOption) (*DeleteUserResp, error)
		ResetUserPassword(ctx context.Context, in *ResetUserPasswordReq, opts ...grpc.CallOption) (*ResetUserPasswordResp, error)
		UpdateSelf(ctx context.Context, in *UpdateSelfReq, opts ...grpc.CallOption) (*UpdateSelfResp, error)
		UpdateUser(ctx context.Context, in *UpdateUserReq, opts ...grpc.CallOption) (*UpdateUserResp, error)
		BanUser(ctx context.Context, in *BanUserReq, opts ...grpc.CallOption) (*BanUserResp, error)
		UnBanUser(ctx context.Context, in *UnBanUserReq, opts ...grpc.CallOption) (*UnBanUserResp, error)
	}

	defaultAdminService struct {
		cli zrpc.Client
	}
)

func NewAdminService(cli zrpc.Client) AdminService {
	return &defaultAdminService{
		cli: cli,
	}
}

func (m *defaultAdminService) GetUser(ctx context.Context, in *GetUserReq, opts ...grpc.CallOption) (*GetUserResp, error) {
	client := pb.NewAdminServiceClient(m.cli.Conn())
	return client.GetUser(ctx, in, opts...)
}

func (m *defaultAdminService) GetUserList(ctx context.Context, in *GetUserListReq, opts ...grpc.CallOption) (*GetUserListResp, error) {
	client := pb.NewAdminServiceClient(m.cli.Conn())
	return client.GetUserList(ctx, in, opts...)
}

func (m *defaultAdminService) GetSelf(ctx context.Context, in *GetSelfReq, opts ...grpc.CallOption) (*GetSelfResp, error) {
	client := pb.NewAdminServiceClient(m.cli.Conn())
	return client.GetSelf(ctx, in, opts...)
}

func (m *defaultAdminService) CreateAdmin(ctx context.Context, in *CreateAdminReq, opts ...grpc.CallOption) (*CreateAdminResp, error) {
	client := pb.NewAdminServiceClient(m.cli.Conn())
	return client.CreateAdmin(ctx, in, opts...)
}

func (m *defaultAdminService) Login(ctx context.Context, in *LoginReq, opts ...grpc.CallOption) (*LoginResp, error) {
	client := pb.NewAdminServiceClient(m.cli.Conn())
	return client.Login(ctx, in, opts...)
}

func (m *defaultAdminService) DeleteUser(ctx context.Context, in *DeleteUserReq, opts ...grpc.CallOption) (*DeleteUserResp, error) {
	client := pb.NewAdminServiceClient(m.cli.Conn())
	return client.DeleteUser(ctx, in, opts...)
}

func (m *defaultAdminService) ResetUserPassword(ctx context.Context, in *ResetUserPasswordReq, opts ...grpc.CallOption) (*ResetUserPasswordResp, error) {
	client := pb.NewAdminServiceClient(m.cli.Conn())
	return client.ResetUserPassword(ctx, in, opts...)
}

func (m *defaultAdminService) UpdateSelf(ctx context.Context, in *UpdateSelfReq, opts ...grpc.CallOption) (*UpdateSelfResp, error) {
	client := pb.NewAdminServiceClient(m.cli.Conn())
	return client.UpdateSelf(ctx, in, opts...)
}

func (m *defaultAdminService) UpdateUser(ctx context.Context, in *UpdateUserReq, opts ...grpc.CallOption) (*UpdateUserResp, error) {
	client := pb.NewAdminServiceClient(m.cli.Conn())
	return client.UpdateUser(ctx, in, opts...)
}

func (m *defaultAdminService) BanUser(ctx context.Context, in *BanUserReq, opts ...grpc.CallOption) (*BanUserResp, error) {
	client := pb.NewAdminServiceClient(m.cli.Conn())
	return client.BanUser(ctx, in, opts...)
}

func (m *defaultAdminService) UnBanUser(ctx context.Context, in *UnBanUserReq, opts ...grpc.CallOption) (*UnBanUserResp, error) {
	client := pb.NewAdminServiceClient(m.cli.Conn())
	return client.UnBanUser(ctx, in, opts...)
}
