// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: proto/points.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddPointsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	UserPoints    int64                  `protobuf:"varint,2,opt,name=user_points,json=userPoints,proto3" json:"user_points,omitempty"`
	RequestId     int64                  `protobuf:"varint,3,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	AddPoints     int64                  `protobuf:"varint,4,opt,name=add_points,json=addPoints,proto3" json:"add_points,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddPointsReq) Reset() {
	*x = AddPointsReq{}
	mi := &file_proto_points_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddPointsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddPointsReq) ProtoMessage() {}

func (x *AddPointsReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_points_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddPointsReq.ProtoReflect.Descriptor instead.
func (*AddPointsReq) Descriptor() ([]byte, []int) {
	return file_proto_points_proto_rawDescGZIP(), []int{0}
}

func (x *AddPointsReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *AddPointsReq) GetUserPoints() int64 {
	if x != nil {
		return x.UserPoints
	}
	return 0
}

func (x *AddPointsReq) GetRequestId() int64 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

func (x *AddPointsReq) GetAddPoints() int64 {
	if x != nil {
		return x.AddPoints
	}
	return 0
}

type AddPointsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddPointsResp) Reset() {
	*x = AddPointsResp{}
	mi := &file_proto_points_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddPointsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddPointsResp) ProtoMessage() {}

func (x *AddPointsResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_points_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddPointsResp.ProtoReflect.Descriptor instead.
func (*AddPointsResp) Descriptor() ([]byte, []int) {
	return file_proto_points_proto_rawDescGZIP(), []int{1}
}

func (x *AddPointsResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AddPointsResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type DecPointsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	UserPoints    int64                  `protobuf:"varint,2,opt,name=user_points,json=userPoints,proto3" json:"user_points,omitempty"`
	RequestId     int64                  `protobuf:"varint,3,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	DecPoints     int64                  `protobuf:"varint,4,opt,name=dec_points,json=decPoints,proto3" json:"dec_points,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DecPointsReq) Reset() {
	*x = DecPointsReq{}
	mi := &file_proto_points_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecPointsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecPointsReq) ProtoMessage() {}

func (x *DecPointsReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_points_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecPointsReq.ProtoReflect.Descriptor instead.
func (*DecPointsReq) Descriptor() ([]byte, []int) {
	return file_proto_points_proto_rawDescGZIP(), []int{2}
}

func (x *DecPointsReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *DecPointsReq) GetUserPoints() int64 {
	if x != nil {
		return x.UserPoints
	}
	return 0
}

func (x *DecPointsReq) GetRequestId() int64 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

func (x *DecPointsReq) GetDecPoints() int64 {
	if x != nil {
		return x.DecPoints
	}
	return 0
}

type DecPointsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DecPointsResp) Reset() {
	*x = DecPointsResp{}
	mi := &file_proto_points_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecPointsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecPointsResp) ProtoMessage() {}

func (x *DecPointsResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_points_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecPointsResp.ProtoReflect.Descriptor instead.
func (*DecPointsResp) Descriptor() ([]byte, []int) {
	return file_proto_points_proto_rawDescGZIP(), []int{3}
}

func (x *DecPointsResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DecPointsResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_points_proto protoreflect.FileDescriptor

const file_proto_points_proto_rawDesc = "" +
	"\n" +
	"\x12proto/points.proto\x12\x06points\"\x86\x01\n" +
	"\fAddPointsReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1f\n" +
	"\vuser_points\x18\x02 \x01(\x03R\n" +
	"userPoints\x12\x1d\n" +
	"\n" +
	"request_id\x18\x03 \x01(\x03R\trequestId\x12\x1d\n" +
	"\n" +
	"add_points\x18\x04 \x01(\x03R\taddPoints\"C\n" +
	"\rAddPointsResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x86\x01\n" +
	"\fDecPointsReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1f\n" +
	"\vuser_points\x18\x02 \x01(\x03R\n" +
	"userPoints\x12\x1d\n" +
	"\n" +
	"request_id\x18\x03 \x01(\x03R\trequestId\x12\x1d\n" +
	"\n" +
	"dec_points\x18\x04 \x01(\x03R\tdecPoints\"C\n" +
	"\rDecPointsResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\x83\x01\n" +
	"\rPointsService\x128\n" +
	"\tAddPoints\x12\x14.points.AddPointsReq\x1a\x15.points.AddPointsResp\x128\n" +
	"\tDecPoints\x12\x14.points.DecPointsReq\x1a\x15.points.DecPointsRespB\x03Z\x01.b\x06proto3"

var (
	file_proto_points_proto_rawDescOnce sync.Once
	file_proto_points_proto_rawDescData []byte
)

func file_proto_points_proto_rawDescGZIP() []byte {
	file_proto_points_proto_rawDescOnce.Do(func() {
		file_proto_points_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_points_proto_rawDesc), len(file_proto_points_proto_rawDesc)))
	})
	return file_proto_points_proto_rawDescData
}

var file_proto_points_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_points_proto_goTypes = []any{
	(*AddPointsReq)(nil),  // 0: points.AddPointsReq
	(*AddPointsResp)(nil), // 1: points.AddPointsResp
	(*DecPointsReq)(nil),  // 2: points.DecPointsReq
	(*DecPointsResp)(nil), // 3: points.DecPointsResp
}
var file_proto_points_proto_depIdxs = []int32{
	0, // 0: points.PointsService.AddPoints:input_type -> points.AddPointsReq
	2, // 1: points.PointsService.DecPoints:input_type -> points.DecPointsReq
	1, // 2: points.PointsService.AddPoints:output_type -> points.AddPointsResp
	3, // 3: points.PointsService.DecPoints:output_type -> points.DecPointsResp
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_points_proto_init() }
func file_proto_points_proto_init() {
	if File_proto_points_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_points_proto_rawDesc), len(file_proto_points_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_points_proto_goTypes,
		DependencyIndexes: file_proto_points_proto_depIdxs,
		MessageInfos:      file_proto_points_proto_msgTypes,
	}.Build()
	File_proto_points_proto = out.File
	file_proto_points_proto_goTypes = nil
	file_proto_points_proto_depIdxs = nil
}
