// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: proto/points.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PointsRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ArticleId     string                 `protobuf:"bytes,1,opt,name=article_id,json=articleId,proto3" json:"article_id,omitempty"`
	CoinCount     int32                  `protobuf:"varint,2,opt,name=coin_count,json=coinCount,proto3" json:"coin_count,omitempty"`
	Date          string                 `protobuf:"bytes,3,opt,name=date,proto3" json:"date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PointsRecord) Reset() {
	*x = PointsRecord{}
	mi := &file_proto_points_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PointsRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PointsRecord) ProtoMessage() {}

func (x *PointsRecord) ProtoReflect() protoreflect.Message {
	mi := &file_proto_points_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PointsRecord.ProtoReflect.Descriptor instead.
func (*PointsRecord) Descriptor() ([]byte, []int) {
	return file_proto_points_proto_rawDescGZIP(), []int{0}
}

func (x *PointsRecord) GetArticleId() string {
	if x != nil {
		return x.ArticleId
	}
	return ""
}

func (x *PointsRecord) GetCoinCount() int32 {
	if x != nil {
		return x.CoinCount
	}
	return 0
}

func (x *PointsRecord) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

type SignInReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignInReq) Reset() {
	*x = SignInReq{}
	mi := &file_proto_points_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignInReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignInReq) ProtoMessage() {}

func (x *SignInReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_points_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignInReq.ProtoReflect.Descriptor instead.
func (*SignInReq) Descriptor() ([]byte, []int) {
	return file_proto_points_proto_rawDescGZIP(), []int{1}
}

func (x *SignInReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type SignInResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignInResp) Reset() {
	*x = SignInResp{}
	mi := &file_proto_points_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignInResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignInResp) ProtoMessage() {}

func (x *SignInResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_points_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignInResp.ProtoReflect.Descriptor instead.
func (*SignInResp) Descriptor() ([]byte, []int) {
	return file_proto_points_proto_rawDescGZIP(), []int{2}
}

func (x *SignInResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SignInResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type AddArticlePointReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ArticleId     string                 `protobuf:"bytes,2,opt,name=article_id,json=articleId,proto3" json:"article_id,omitempty"`
	CoinCount     int64                  `protobuf:"varint,3,opt,name=coin_count,json=coinCount,proto3" json:"coin_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddArticlePointReq) Reset() {
	*x = AddArticlePointReq{}
	mi := &file_proto_points_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddArticlePointReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddArticlePointReq) ProtoMessage() {}

func (x *AddArticlePointReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_points_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddArticlePointReq.ProtoReflect.Descriptor instead.
func (*AddArticlePointReq) Descriptor() ([]byte, []int) {
	return file_proto_points_proto_rawDescGZIP(), []int{3}
}

func (x *AddArticlePointReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AddArticlePointReq) GetArticleId() string {
	if x != nil {
		return x.ArticleId
	}
	return ""
}

func (x *AddArticlePointReq) GetCoinCount() int64 {
	if x != nil {
		return x.CoinCount
	}
	return 0
}

type AddArticlePointResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddArticlePointResp) Reset() {
	*x = AddArticlePointResp{}
	mi := &file_proto_points_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddArticlePointResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddArticlePointResp) ProtoMessage() {}

func (x *AddArticlePointResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_points_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddArticlePointResp.ProtoReflect.Descriptor instead.
func (*AddArticlePointResp) Descriptor() ([]byte, []int) {
	return file_proto_points_proto_rawDescGZIP(), []int{4}
}

func (x *AddArticlePointResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AddArticlePointResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetUserAddPointHistoryReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserAddPointHistoryReq) Reset() {
	*x = GetUserAddPointHistoryReq{}
	mi := &file_proto_points_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserAddPointHistoryReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserAddPointHistoryReq) ProtoMessage() {}

func (x *GetUserAddPointHistoryReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_points_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserAddPointHistoryReq.ProtoReflect.Descriptor instead.
func (*GetUserAddPointHistoryReq) Descriptor() ([]byte, []int) {
	return file_proto_points_proto_rawDescGZIP(), []int{5}
}

func (x *GetUserAddPointHistoryReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetUserAddPointHistoryResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PointsRecord  []*PointsRecord        `protobuf:"bytes,1,rep,name=points_record,json=pointsRecord,proto3" json:"points_record,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserAddPointHistoryResp) Reset() {
	*x = GetUserAddPointHistoryResp{}
	mi := &file_proto_points_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserAddPointHistoryResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserAddPointHistoryResp) ProtoMessage() {}

func (x *GetUserAddPointHistoryResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_points_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserAddPointHistoryResp.ProtoReflect.Descriptor instead.
func (*GetUserAddPointHistoryResp) Descriptor() ([]byte, []int) {
	return file_proto_points_proto_rawDescGZIP(), []int{6}
}

func (x *GetUserAddPointHistoryResp) GetPointsRecord() []*PointsRecord {
	if x != nil {
		return x.PointsRecord
	}
	return nil
}

var File_proto_points_proto protoreflect.FileDescriptor

const file_proto_points_proto_rawDesc = "" +
	"\n" +
	"\x12proto/points.proto\x12\x06points\"`\n" +
	"\fPointsRecord\x12\x1d\n" +
	"\n" +
	"article_id\x18\x01 \x01(\tR\tarticleId\x12\x1d\n" +
	"\n" +
	"coin_count\x18\x02 \x01(\x05R\tcoinCount\x12\x12\n" +
	"\x04date\x18\x03 \x01(\tR\x04date\"$\n" +
	"\tSignInReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"@\n" +
	"\n" +
	"SignInResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"k\n" +
	"\x12AddArticlePointReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"article_id\x18\x02 \x01(\tR\tarticleId\x12\x1d\n" +
	"\n" +
	"coin_count\x18\x03 \x01(\x03R\tcoinCount\"I\n" +
	"\x13AddArticlePointResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"4\n" +
	"\x19GetUserAddPointHistoryReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"W\n" +
	"\x1aGetUserAddPointHistoryResp\x129\n" +
	"\rpoints_record\x18\x01 \x03(\v2\x14.points.PointsRecordR\fpointsRecord2\xed\x01\n" +
	"\rPointsService\x12/\n" +
	"\x06SignIn\x12\x11.points.SignInReq\x1a\x12.points.SignInResp\x12J\n" +
	"\x0fAddArticlePoint\x12\x1a.points.AddArticlePointReq\x1a\x1b.points.AddArticlePointResp\x12_\n" +
	"\x16GetUserAddPointHistory\x12!.points.GetUserAddPointHistoryReq\x1a\".points.GetUserAddPointHistoryRespB\x03Z\x01.b\x06proto3"

var (
	file_proto_points_proto_rawDescOnce sync.Once
	file_proto_points_proto_rawDescData []byte
)

func file_proto_points_proto_rawDescGZIP() []byte {
	file_proto_points_proto_rawDescOnce.Do(func() {
		file_proto_points_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_points_proto_rawDesc), len(file_proto_points_proto_rawDesc)))
	})
	return file_proto_points_proto_rawDescData
}

var file_proto_points_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_points_proto_goTypes = []any{
	(*PointsRecord)(nil),               // 0: points.PointsRecord
	(*SignInReq)(nil),                  // 1: points.SignInReq
	(*SignInResp)(nil),                 // 2: points.SignInResp
	(*AddArticlePointReq)(nil),         // 3: points.AddArticlePointReq
	(*AddArticlePointResp)(nil),        // 4: points.AddArticlePointResp
	(*GetUserAddPointHistoryReq)(nil),  // 5: points.GetUserAddPointHistoryReq
	(*GetUserAddPointHistoryResp)(nil), // 6: points.GetUserAddPointHistoryResp
}
var file_proto_points_proto_depIdxs = []int32{
	0, // 0: points.GetUserAddPointHistoryResp.points_record:type_name -> points.PointsRecord
	1, // 1: points.PointsService.SignIn:input_type -> points.SignInReq
	3, // 2: points.PointsService.AddArticlePoint:input_type -> points.AddArticlePointReq
	5, // 3: points.PointsService.GetUserAddPointHistory:input_type -> points.GetUserAddPointHistoryReq
	2, // 4: points.PointsService.SignIn:output_type -> points.SignInResp
	4, // 5: points.PointsService.AddArticlePoint:output_type -> points.AddArticlePointResp
	6, // 6: points.PointsService.GetUserAddPointHistory:output_type -> points.GetUserAddPointHistoryResp
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_points_proto_init() }
func file_proto_points_proto_init() {
	if File_proto_points_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_points_proto_rawDesc), len(file_proto_points_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_points_proto_goTypes,
		DependencyIndexes: file_proto_points_proto_depIdxs,
		MessageInfos:      file_proto_points_proto_msgTypes,
	}.Build()
	File_proto_points_proto = out.File
	file_proto_points_proto_goTypes = nil
	file_proto_points_proto_depIdxs = nil
}
