// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: proto/points.proto

package __

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PointsService_AddPoints_FullMethodName = "/points.PointsService/AddPoints"
	PointsService_DecPoints_FullMethodName = "/points.PointsService/DecPoints"
)

// PointsServiceClient is the client API for PointsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PointsServiceClient interface {
	AddPoints(ctx context.Context, in *AddPointsReq, opts ...grpc.CallOption) (*AddPointsResp, error)
	DecPoints(ctx context.Context, in *DecPointsReq, opts ...grpc.CallOption) (*DecPointsResp, error)
}

type pointsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPointsServiceClient(cc grpc.ClientConnInterface) PointsServiceClient {
	return &pointsServiceClient{cc}
}

func (c *pointsServiceClient) AddPoints(ctx context.Context, in *AddPointsReq, opts ...grpc.CallOption) (*AddPointsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddPointsResp)
	err := c.cc.Invoke(ctx, PointsService_AddPoints_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pointsServiceClient) DecPoints(ctx context.Context, in *DecPointsReq, opts ...grpc.CallOption) (*DecPointsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DecPointsResp)
	err := c.cc.Invoke(ctx, PointsService_DecPoints_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PointsServiceServer is the server API for PointsService service.
// All implementations must embed UnimplementedPointsServiceServer
// for forward compatibility.
type PointsServiceServer interface {
	AddPoints(context.Context, *AddPointsReq) (*AddPointsResp, error)
	DecPoints(context.Context, *DecPointsReq) (*DecPointsResp, error)
	mustEmbedUnimplementedPointsServiceServer()
}

// UnimplementedPointsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPointsServiceServer struct{}

func (UnimplementedPointsServiceServer) AddPoints(context.Context, *AddPointsReq) (*AddPointsResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddPoints not implemented")
}
func (UnimplementedPointsServiceServer) DecPoints(context.Context, *DecPointsReq) (*DecPointsResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DecPoints not implemented")
}
func (UnimplementedPointsServiceServer) mustEmbedUnimplementedPointsServiceServer() {}
func (UnimplementedPointsServiceServer) testEmbeddedByValue()                       {}

// UnsafePointsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PointsServiceServer will
// result in compilation errors.
type UnsafePointsServiceServer interface {
	mustEmbedUnimplementedPointsServiceServer()
}

func RegisterPointsServiceServer(s grpc.ServiceRegistrar, srv PointsServiceServer) {
	// If the following call pancis, it indicates UnimplementedPointsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PointsService_ServiceDesc, srv)
}

func _PointsService_AddPoints_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddPointsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PointsServiceServer).AddPoints(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PointsService_AddPoints_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PointsServiceServer).AddPoints(ctx, req.(*AddPointsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _PointsService_DecPoints_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DecPointsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PointsServiceServer).DecPoints(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PointsService_DecPoints_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PointsServiceServer).DecPoints(ctx, req.(*DecPointsReq))
	}
	return interceptor(ctx, in, info, handler)
}

// PointsService_ServiceDesc is the grpc.ServiceDesc for PointsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PointsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "points.PointsService",
	HandlerType: (*PointsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddPoints",
			Handler:    _PointsService_AddPoints_Handler,
		},
		{
			MethodName: "DecPoints",
			Handler:    _PointsService_DecPoints_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/points.proto",
}
