// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type AdminInfo struct {
	Uid       int64             `json:"uid,string"`
	Username  string            `json:"username"`
	Email     string            `json:"email"`
	Extrainfo map[string]string `json:"extra_info,omitempty"`
}

type BanUserReq struct {
	Uid int64 `json:"uid,string"`
}

type BanUserResp struct {
	Success bool `json:"success"`
}

type CreateAdminReq struct {
	Username  string            `json:"username"`
	Password  string            `json:"password"`
	Email     string            `json:"email,omitempty"`
	Extrainfo map[string]string `json:"extra_info,omitempty"`
}

type CreateAdminResp struct {
	Uid int64 `json:"uid,string"`
}

type DeleteUserReq struct {
	Uid int64 `json:"uid,string"`
}

type DeleteUserResp struct {
	Success bool `json:"success"`
}

type GetSelfReq struct {
}

type GetSelfResp struct {
	Admin AdminInfo `json:"admin"`
}

type GetUserListReq struct {
	Page     int64  `form:"page,default=1"`
	PageSize int64  `form:"page_size,default=20"`
	Keyword  string `form:"keyword,omitempty"`
}

type GetUserListResp struct {
	List  []UserInfo `json:"list"`
	Total int64      `json:"total"`
}

type GetUserReq struct {
	Uid int64 `form:"uid,string"`
}

type GetUserResp struct {
	User  UserInfo `json:"user,omitempty"`
	Found bool     `json:"found"`
}

type LoginReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type LoginResp struct {
	Token string `json:"token"`
}

type ResetUserPasswordReq struct {
	Uid int64 `json:"uid,string"`
}

type ResetUserPasswordResp struct {
	Success bool `json:"success"`
}

type UnBanUserReq struct {
	Uid int64 `json:"uid,string"`
}

type UnBanUserResp struct {
	Success bool `json:"success"`
}

type UpdateSelfReq struct {
	Username  string            `json:"username,omitempty"`
	Password  string            `json:"password,omitempty"`
	Email     string            `json:"email,omitempty"`
	Extrainfo map[string]string `json:"extra_info,omitempty"`
}

type UpdateSelfResp struct {
	Success bool      `json:"success"`
	Admin   AdminInfo `json:"admin"`
}

type UpdateUserReq struct {
	Uid       int64             `json:"uid,string"`
	Username  string            `json:"username,omitempty"`
	Password  string            `json:"password,omitempty"`
	Email     string            `json:"email,omitempty"`
	Extrainfo map[string]string `json:"extra_info,omitempty"`
}

type UpdateUserResp struct {
	Success bool     `json:"success"`
	User    UserInfo `json:"user"`
}

type UserInfo struct {
	Uid       int64             `json:"uid,string"`
	Username  string            `json:"username"`
	Status    int64             `json:"status"`
	Email     string            `json:"email,omitempty"`
	Extrainfo map[string]string `json:"extra_info,omitempty"`
}
