// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: task.proto

package server

import (
	"context"

	"sea-try-go/service/task/rpc/internal/logic"
	"sea-try-go/service/task/rpc/internal/svc"
	"sea-try-go/service/task/rpc/pb"
)

type TaskServiceServer struct {
	svcCtx *svc.ServiceContext
	__.UnimplementedTaskServiceServer
}

func NewTaskServiceServer(svcCtx *svc.ServiceContext) *TaskServiceServer {
	return &TaskServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *TaskServiceServer) GetTask(ctx context.Context, in *__.GetTaskReq) (*__.GetTaskResp, error) {
	l := logic.NewGetTaskLogic(ctx, s.svcCtx)
	return l.GetTask(in)
}

func (s *TaskServiceServer) CreateTask(ctx context.Context, in *__.CreateTaskReq) (*__.CreateTaskResp, error) {
	l := logic.NewCreateTaskLogic(ctx, s.svcCtx)
	return l.CreateTask(in)
}

func (s *TaskServiceServer) UpdateTask(ctx context.Context, in *__.UpdateTaskReq) (*__.UpdateTaskResp, error) {
	l := logic.NewUpdateTaskLogic(ctx, s.svcCtx)
	return l.UpdateTask(in)
}

func (s *TaskServiceServer) DeleteTask(ctx context.Context, in *__.DeleteTaskReq) (*__.DeleteTaskResp, error) {
	l := logic.NewDeleteTaskLogic(ctx, s.svcCtx)
	return l.DeleteTask(in)
}
