// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: admin.proto

package server

import (
	"context"
	"sea-try-go/service/user/admin/rpc/internal/logic"
	"sea-try-go/service/user/admin/rpc/internal/svc"
	"sea-try-go/service/user/admin/rpc/pb"
)

type AdminServiceServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedAdminServiceServer
}

func NewAdminServiceServer(svcCtx *svc.ServiceContext) *AdminServiceServer {
	return &AdminServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *AdminServiceServer) GetUser(ctx context.Context, in *pb.GetUserReq) (*pb.GetUserResp, error) {
	l := logic.NewGetUserLogic(ctx, s.svcCtx)
	return l.GetUser(in)
}

func (s *AdminServiceServer) GetUserList(ctx context.Context, in *pb.GetUserListReq) (*pb.GetUserListResp, error) {
	l := logic.NewGetUserListLogic(ctx, s.svcCtx)
	return l.GetUserList(in)
}

func (s *AdminServiceServer) GetSelf(ctx context.Context, in *pb.GetSelfReq) (*pb.GetSelfResp, error) {
	l := logic.NewGetSelfLogic(ctx, s.svcCtx)
	return l.GetSelf(in)
}

func (s *AdminServiceServer) CreateAdmin(ctx context.Context, in *pb.CreateAdminReq) (*pb.CreateAdminResp, error) {
	l := logic.NewCreateAdminLogic(ctx, s.svcCtx)
	return l.CreateAdmin(in)
}

func (s *AdminServiceServer) Login(ctx context.Context, in *pb.LoginReq) (*pb.LoginResp, error) {
	l := logic.NewLoginLogic(ctx, s.svcCtx)
	return l.Login(in)
}

func (s *AdminServiceServer) DeleteUser(ctx context.Context, in *pb.DeleteUserReq) (*pb.DeleteUserResp, error) {
	l := logic.NewDeleteUserLogic(ctx, s.svcCtx)
	return l.DeleteUser(in)
}

func (s *AdminServiceServer) ResetUserPassword(ctx context.Context, in *pb.ResetUserPasswordReq) (*pb.ResetUserPasswordResp, error) {
	l := logic.NewResetUserPasswordLogic(ctx, s.svcCtx)
	return l.ResetUserPassword(in)
}

func (s *AdminServiceServer) UpdateSelf(ctx context.Context, in *pb.UpdateSelfReq) (*pb.UpdateSelfResp, error) {
	l := logic.NewUpdateSelfLogic(ctx, s.svcCtx)
	return l.UpdateSelf(in)
}

func (s *AdminServiceServer) UpdateUser(ctx context.Context, in *pb.UpdateUserReq) (*pb.UpdateUserResp, error) {
	l := logic.NewUpdateUserLogic(ctx, s.svcCtx)
	return l.UpdateUser(in)
}

func (s *AdminServiceServer) BanUser(ctx context.Context, in *pb.BanUserReq) (*pb.BanUserResp, error) {
	l := logic.NewBanUserLogic(ctx, s.svcCtx)
	return l.BanUser(in)
}

func (s *AdminServiceServer) UnBanUser(ctx context.Context, in *pb.UnBanUserReq) (*pb.UnBanUserResp, error) {
	l := logic.NewUnBanUserLogic(ctx, s.svcCtx)
	return l.UnBanUser(in)
}
