// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: points.proto

package server

import (
	"context"

	"sea-try-go/service/points/rpc/internal/logic"
	"sea-try-go/service/points/rpc/internal/svc"
	"sea-try-go/service/points/rpc/pb"
)

type PointsServiceServer struct {
	svcCtx *svc.ServiceContext
	__.UnimplementedPointsServiceServer
}

func NewPointsServiceServer(svcCtx *svc.ServiceContext) *PointsServiceServer {
	return &PointsServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *PointsServiceServer) SignIn(ctx context.Context, in *__.SignInReq) (*__.SignInResp, error) {
	l := logic.NewSignInLogic(ctx, s.svcCtx)
	return l.SignIn(in)
}

func (s *PointsServiceServer) AddArticlePoint(ctx context.Context, in *__.AddArticlePointReq) (*__.AddArticlePointResp, error) {
	l := logic.NewAddArticlePointLogic(ctx, s.svcCtx)
	return l.AddArticlePoint(in)
}

func (s *PointsServiceServer) GetUserAddPointHistory(ctx context.Context, in *__.GetUserAddPointHistoryReq) (*__.GetUserAddPointHistoryResp, error) {
	l := logic.NewGetUserAddPointHistoryLogic(ctx, s.svcCtx)
	return l.GetUserAddPointHistory(in)
}
