// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: points.proto

package server

import (
	"context"

	"sea-try-go/service/points/rpc/internal/logic"
	"sea-try-go/service/points/rpc/internal/svc"
	"sea-try-go/service/points/rpc/pb"
)

type PointsServiceServer struct {
	svcCtx *svc.ServiceContext
	__.UnimplementedPointsServiceServer
}

func NewPointsServiceServer(svcCtx *svc.ServiceContext) *PointsServiceServer {
	return &PointsServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *PointsServiceServer) AddPoints(ctx context.Context, in *__.AddPointsReq) (*__.AddPointsResp, error) {
	l := logic.NewAddPointsLogic(ctx, s.svcCtx)
	return l.AddPoints(in)
}

func (s *PointsServiceServer) DecPoints(ctx context.Context, in *__.DecPointsReq) (*__.DecPointsResp, error) {
	l := logic.NewDecPointsLogic(ctx, s.svcCtx)
	return l.DecPoints(in)
}
