// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	admin "sea-try-go/service/user/admin/api/internal/handler/admin"
	"sea-try-go/service/user/admin/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/admin/create",
				Handler: admin.CreateHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/admin/login",
				Handler: admin.LoginHandler(serverCtx),
			},
		},
		rest.WithPrefix("/admincenter/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/admin/banuser",
				Handler: admin.BanuserHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/admin/delete",
				Handler: admin.DeleteHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/admin/getself",
				Handler: admin.GetselfHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/admin/getuser",
				Handler: admin.GetuserHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/admin/getuserlist",
				Handler: admin.GetuserlistHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/admin/resetuserpassword",
				Handler: admin.ResetuserpasswordHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/admin/unbanuser",
				Handler: admin.UnbanuserHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/admin/update",
				Handler: admin.UpdateHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/admin/updateuser",
				Handler: admin.UpdateuserHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.AdminAuth.AccessSecret),
		rest.WithPrefix("/admincenter/v1"),
	)
}
