// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	user "sea-try-go/service/user/api/internal/handler/user"
	"sea-try-go/service/user/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/user/login",
				Handler: user.LoginHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/user/register",
				Handler: user.RegisterHandler(serverCtx),
			},
		},
		rest.WithPrefix("/usercenter/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodDelete,
				Path:    "/user/delete",
				Handler: user.DeleteuserHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/user/get",
				Handler: user.GetuserHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/user/logout",
				Handler: user.LogoutHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/user/update",
				Handler: user.UpdateuserHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.UserAuth.AccessSecret),
		rest.WithPrefix("/usercenter/v1"),
	)
}
