// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: points.proto

package pointsservice

import (
	"context"

	"sea-try-go/service/points/rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AddArticlePointReq         = __.AddArticlePointReq
	AddArticlePointResp        = __.AddArticlePointResp
	GetUserAddPointHistoryReq  = __.GetUserAddPointHistoryReq
	GetUserAddPointHistoryResp = __.GetUserAddPointHistoryResp
	PointsRecord               = __.PointsRecord
	SignInReq                  = __.SignInReq
	SignInResp                 = __.SignInResp

	PointsService interface {
		SignIn(ctx context.Context, in *SignInReq, opts ...grpc.CallOption) (*SignInResp, error)
		AddArticlePoint(ctx context.Context, in *AddArticlePointReq, opts ...grpc.CallOption) (*AddArticlePointResp, error)
		GetUserAddPointHistory(ctx context.Context, in *GetUserAddPointHistoryReq, opts ...grpc.CallOption) (*GetUserAddPointHistoryResp, error)
	}

	defaultPointsService struct {
		cli zrpc.Client
	}
)

func NewPointsService(cli zrpc.Client) PointsService {
	return &defaultPointsService{
		cli: cli,
	}
}

func (m *defaultPointsService) SignIn(ctx context.Context, in *SignInReq, opts ...grpc.CallOption) (*SignInResp, error) {
	client := __.NewPointsServiceClient(m.cli.Conn())
	return client.SignIn(ctx, in, opts...)
}

func (m *defaultPointsService) AddArticlePoint(ctx context.Context, in *AddArticlePointReq, opts ...grpc.CallOption) (*AddArticlePointResp, error) {
	client := __.NewPointsServiceClient(m.cli.Conn())
	return client.AddArticlePoint(ctx, in, opts...)
}

func (m *defaultPointsService) GetUserAddPointHistory(ctx context.Context, in *GetUserAddPointHistoryReq, opts ...grpc.CallOption) (*GetUserAddPointHistoryResp, error) {
	client := __.NewPointsServiceClient(m.cli.Conn())
	return client.GetUserAddPointHistory(ctx, in, opts...)
}
