// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: points.proto

package pointsservice

import (
	"context"

	"sea-try-go/service/points/rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AddPointsReq  = __.AddPointsReq
	AddPointsResp = __.AddPointsResp
	DecPointsReq  = __.DecPointsReq
	DecPointsResp = __.DecPointsResp

	PointsService interface {
		AddPoints(ctx context.Context, in *AddPointsReq, opts ...grpc.CallOption) (*AddPointsResp, error)
		DecPoints(ctx context.Context, in *DecPointsReq, opts ...grpc.CallOption) (*DecPointsResp, error)
	}

	defaultPointsService struct {
		cli zrpc.Client
	}
)

func NewPointsService(cli zrpc.Client) PointsService {
	return &defaultPointsService{
		cli: cli,
	}
}

func (m *defaultPointsService) AddPoints(ctx context.Context, in *AddPointsReq, opts ...grpc.CallOption) (*AddPointsResp, error) {
	client := __.NewPointsServiceClient(m.cli.Conn())
	return client.AddPoints(ctx, in, opts...)
}

func (m *defaultPointsService) DecPoints(ctx context.Context, in *DecPointsReq, opts ...grpc.CallOption) (*DecPointsResp, error) {
	client := __.NewPointsServiceClient(m.cli.Conn())
	return client.DecPoints(ctx, in, opts...)
}
