// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type CreateUserReq struct {
	Username  string            `json:"username"`
	Password  string            `json:"password"`
	Email     string            `json:"email,omitempty"`
	Extrainfo map[string]string `json:"extra_info,omitempty"`
}

type CreateUserResp struct {
	Uid int64 `json:"uid,string"`
}

type DeleteUserReq struct {
}

type DeleteUserResp struct {
	Success bool `json:"success"`
}

type GetUserReq struct {
}

type GetUserResp struct {
	User  UserInfo `json:"user,omitempty"`
	Found bool     `json:"found"`
}

type LoginReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type LoginResp struct {
	Token string `json:"token"`
}

type LogoutReq struct {
}

type LogoutResp struct {
	Success bool `json:"success"`
}

type UpdateUserReq struct {
	Username  string            `json:"username,omitempty"`
	Password  string            `json:"password,omitempty"`
	Email     string            `json:"email,omitempty"`
	Extrainfo map[string]string `json:"extra_info,omitempty"`
}

type UpdateUserResp struct {
	User UserInfo `json:"user"`
}

type UserInfo struct {
	Uid       int64             `json:"uid,string"`
	Score     uint32            `json:"score"`
	Username  string            `json:"username"`
	Email     string            `json:"email,omitempty"`
	Extrainfo map[string]string `json:"extra_info,omitempty"`
}
