// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type CreateUserReq struct {
	Username  string            `json:"username"`
	Password  string            `json:"password"`
	Email     string            `json:"email,optional"`
	Extrainfo map[string]string `json:"extra_info,optional"`
}

type CreateUserResp struct {
	Id uint64 `json:"id"`
}

type DeleteUserReq struct {
	Id uint64 `json:"id"`
}

type DeleteUserResp struct {
	Success bool `json:"success"`
}

type GetUserReq struct {
	Id uint64 `form:"id"`
}

type GetUserResp struct {
	User  UserInfo `json:"user,optional"`
	Found bool     `json:"found"`
}

type LoginReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type LoginResp struct {
	Token string `json:"token"`
}

type LogoutReq struct {
	Token string `json:"token"`
}

type LogoutResp struct {
	Success bool `json:"success"`
}

type UpdateUserReq struct {
	Id        uint64            `json:"id"`
	Username  string            `json:"username,optional"`
	Password  string            `json:"password,optional"`
	Email     string            `json:"email,optional"`
	Extrainfo map[string]string `json:"extra_info,optional"`
}

type UpdateUserResp struct {
	User UserInfo `json:"user"`
}

type UserInfo struct {
	Id        uint64            `json:"id"`
	Username  string            `json:"username"`
	Email     string            `json:"email,optional"`
	Extrainfo map[string]string `json:"extra_info,optional"`
}
